name: staff_breeze
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  awesome_ripple_animation: ^0.6.0
  calendar_date_picker2: ^0.3.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dotted_border: ^2.0.0+3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_multi_formatter: ^2.2.1
  flutter_riverpod: ^2.0.2
  flutter_screenutil: ^5.6.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  image_picker: ^0.8.6
  injectable: ^1.5.4
  json_annotation: ^4.7.0
  keyboard_dismisser: ^3.0.0
  quickalert: ^1.0.0
  retrofit: ^3.3.1
  sliding_switch: ^1.1.0
  url_launcher: ^6.1.6

dev_dependencies:

  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  injectable_generator: ^1.5.5
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0
  flutter_launcher_icons: "^0.11.0"
flutter_icons:
  android: "icon_luncher"
  ios: true
  image_path: "assets/images/icon_luncher.png"
  min_sdk_android: 21



flutter:

  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf

    - family: raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-ExtraBold.ttf
        - asset: assets/fonts/Raleway-ExtraLight.ttf
        - asset: assets/fonts/Raleway-Light.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
